Importing and setting values.

In [4]:
import sys
import numpy as np

np.set_printoptions(threshold=sys.maxsize)

## Problem 1: Maze Generation

In [5]:
def generate_maze(dim, p):
    
    maze = np.zeros(dim**2)

    for i in range(int(dim**2 * p)):
        maze[i] = 1
    
    np.random.shuffle(maze)
    
    return maze.reshape((dim, dim))

Testing for problem 1.

In [6]:
testmaze = generate_maze(4, .3)
print(testmaze)

[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]]
